from __future__ import annotations

DEFAULT_VISIBLE_COLUMNS = [
    "country",
    "vertical",
    "current_platforms",
    "domain_migration",
    "cms_migration",
    "domain_fingerprint_strength",
    "domain_shared_signals",
    "sales_buckets",
    "contact_status",
    "technology_spend",
    "total_score",
    "priority_tier",
    "reason",
]


def base_query() -> dict[str, object]:
    return {
        "search": "",
        "exactDomain": "",
        "countries": ["AU", "NZ", "SG"],
        "tiers": ["A", "B", "C", "D"],
        "currentPlatforms": [],
        "recentPlatforms": [],
        "removedPlatforms": [],
        "verticals": [],
        "salesBuckets": [],
        "migrationOnly": False,
        "hasDomainMigration": False,
        "hasCmsMigration": False,
        "domainMigrationStatuses": [],
        "domainConfidenceBands": [],
        "domainFingerprintStrengths": [],
        "domainTldRelationships": [],
        "cmsMigrationStatuses": [],
        "cmsConfidenceLevels": [],
        "hasContact": False,
        "hasMarketing": False,
        "hasCrm": False,
        "hasPayments": False,
        "selectedOnly": False,
        "timelinePlatforms": [],
        "timelineEventTypes": ["current_detected", "recently_added"],
        "timelineDateField": "first_seen",
        "timelineSeenFrom": "",
        "timelineSeenTo": "",
        "cmsMigrationFrom": "",
        "cmsMigrationTo": "",
        "domainMigrationFrom": "",
        "domainMigrationTo": "",
        "migrationTimingOperator": "and",
        "timelineGranularity": "month",
        "pageSize": 100,
    }


def make_preset(
    preset_id: str,
    name: str,
    group: str,
    description: str,
    query_patch: dict[str, object],
    sort_by: str = "total_score",
    sort_direction: str = "desc",
    order: int = 0,
) -> dict[str, object]:
    query = base_query()
    query.update(query_patch)
    return {
        "id": preset_id,
        "name": name,
        "group": group,
        "description": description,
        "order": order,
        "filters": {
            "query": query,
            "visibleColumns": DEFAULT_VISIBLE_COLUMNS,
            "group": group,
            "description": description,
            "order": order,
        },
        "sort": {"sortBy": sort_by, "sortDirection": sort_direction},
    }


BUILTIN_PRESETS = [
    make_preset(
        "builtin_confirmed_migration_shortlist",
        "Confirmed migration shortlist",
        "Reliability",
        "High-trust domain or CMS migrations that are ready for tighter outreach review.",
        {
            "tiers": ["A", "B", "C"],
            "hasContact": True,
            "domainMigrationStatuses": ["confirmed"],
            "cmsMigrationStatuses": ["confirmed"],
        },
        sort_by="total_score",
        order=1,
    ),
    make_preset(
        "builtin_possible_migrations_review",
        "Possible migrations to review",
        "Reliability",
        "Broader migration discovery mode with ambiguity left visible.",
        {
            "tiers": ["A", "B", "C", "D"],
            "domainMigrationStatuses": ["probable", "network", "weak"],
            "cmsMigrationStatuses": ["possible", "overlap", "historic"],
        },
        sort_by="cms_migration_status",
        order=2,
    ),
    make_preset(
        "builtin_redirect_only_domain_candidates",
        "Redirect-only domain candidates",
        "Reliability",
        "Previous-domain matches that still need stronger fingerprint support.",
        {
            "hasDomainMigration": True,
            "domainMigrationStatuses": ["weak"],
            "domainFingerprintStrengths": ["None"],
            "tiers": ["A", "B", "C", "D"],
        },
        sort_by="domain_migration_status",
        order=3,
    ),
    make_preset(
        "builtin_same_tld_domain_migrations",
        "Same-TLD domain migrations",
        "Reliability",
        "Likely same-market domain moves that are usually easier to message in outreach.",
        {
            "hasDomainMigration": True,
            "domainTldRelationships": ["same_tld"],
            "tiers": ["A", "B", "C", "D"],
        },
        sort_by="domain_migration_status",
        order=4,
    ),
    make_preset(
        "builtin_migration_leads",
        "Migration leads",
        "Migration",
        "Previous-domain and CMS migration intelligence in one view.",
        {
            "hasDomainMigration": True,
            "tiers": ["A", "B", "C"],
            "hasContact": True,
        },
        sort_by="domain_migration_status",
        order=5,
    ),
    make_preset(
        "builtin_domain_migration_leads",
        "Domain migration leads",
        "Migration",
        "Prioritise leads with a likely previous domain and supporting fingerprint signals.",
        {
            "hasDomainMigration": True,
            "tiers": ["A", "B", "C"],
            "hasContact": True,
        },
        sort_by="domain_migration_status",
        order=7,
    ),
    make_preset(
        "builtin_cms_migration_leads",
        "CMS migration leads",
        "Migration",
        "Platform migration candidates with recent old/new CMS evidence.",
        {
            "hasCmsMigration": True,
            "tiers": ["A", "B", "C"],
            "hasContact": True,
        },
        sort_by="cms_migration_status",
        order=8,
    ),
    make_preset(
        "builtin_high_confidence_migration",
        "High-confidence migration",
        "Migration",
        "Previous-domain matches with high confidence and strong or moderate fingerprint support.",
        {
            "hasDomainMigration": True,
            "domainMigrationStatuses": ["confirmed"],
            "domainFingerprintStrengths": ["Strong", "Moderate"],
            "tiers": ["A", "B", "C"],
            "hasContact": True,
        },
        sort_by="domain_migration_status",
        order=9,
    ),
    make_preset(
        "builtin_recent_migration",
        "Recent migration",
        "Trigger",
        "Tighter migration leads with the highest urgency signal.",
        {"salesBuckets": ["recent_migration_signal"], "tiers": ["A", "B"], "hasContact": True},
        order=10,
    ),
    make_preset(
        "builtin_switch_to_shopify",
        "Switch to Shopify",
        "Trigger",
        "Sites showing a platform change into Shopify or Shopify Plus.",
        {"salesBuckets": ["switch_to_shopify"], "tiers": ["A", "B"], "hasContact": True},
        order=20,
    ),
    make_preset(
        "builtin_woo_to_shopify",
        "Woo -> Shopify",
        "Trigger",
        "WooCommerce removals that now look like Shopify installs.",
        {"salesBuckets": ["woo_to_shopify", "woo_to_shopify_recent"], "tiers": ["A", "B"], "hasContact": True},
        order=30,
    ),
    make_preset(
        "builtin_woo_to_shopify_plus",
        "Woo -> Shopify Plus",
        "Trigger",
        "Premium WooCommerce migrations into Shopify Plus.",
        {"salesBuckets": ["woo_to_shopify_plus", "woo_to_shopify_plus_recent"], "tiers": ["A", "B"], "hasContact": True},
        order=40,
    ),
    make_preset(
        "builtin_recent_adopters",
        "Recent adopters",
        "Trigger",
        "Recently added platform detections for fresh outreach hooks.",
        {"salesBuckets": ["recent_platform_adopter"], "tiers": ["A", "B"], "hasContact": True},
        order=50,
    ),
    make_preset(
        "builtin_current_shopify",
        "Current Shopify",
        "Current state",
        "The current Shopify install base in AU/NZ/SG.",
        {"salesBuckets": ["current_shopify"], "tiers": ["A", "B", "C"], "hasContact": False},
        sort_by="technology_spend",
        order=60,
    ),
    make_preset(
        "builtin_current_shopify_revenue_stack",
        "Current Shopify revenue stack",
        "Current state",
        "Shopify sites with payments plus marketing or CRM maturity.",
        {"salesBuckets": ["current_shopify_revenue_stack"], "tiers": ["A", "B", "C"], "hasContact": True},
        sort_by="technology_spend",
        order=70,
    ),
    make_preset(
        "builtin_current_shopify_after_woo",
        "Current Shopify after Woo",
        "Current state",
        "Current Shopify rows with a WooCommerce removal signal.",
        {"salesBuckets": ["current_shopify_removed_woocommerce"], "tiers": ["A", "B", "C"], "hasContact": True},
        order=80,
    ),
    make_preset(
        "builtin_current_shopify_plus",
        "Current Shopify Plus",
        "Current state",
        "The current Shopify Plus install base in AU/NZ/SG.",
        {"salesBuckets": ["current_shopify_plus"], "tiers": ["A", "B", "C"], "hasContact": False},
        sort_by="technology_spend",
        order=90,
    ),
    make_preset(
        "builtin_current_shopify_plus_high_spend",
        "Current Shopify Plus high spend",
        "Current state",
        "Higher-spend Shopify Plus accounts for premium outbound.",
        {"salesBuckets": ["current_shopify_plus_high_spend"], "tiers": ["A", "B", "C"], "hasContact": True},
        sort_by="technology_spend",
        order=100,
    ),
    make_preset(
        "builtin_contactable_revenue_stack",
        "Contactable revenue stack",
        "Outreach ready",
        "Direct contacts plus payment and martech evidence.",
        {"salesBuckets": ["contactable_revenue_stack"], "tiers": ["A", "B", "C"], "hasContact": True},
        sort_by="contact_score",
        order=110,
    ),
    make_preset(
        "builtin_contact_ready_ab",
        "Contact-ready A/B",
        "Outreach ready",
        "Higher-priority leads that already have usable contact fields.",
        {"salesBuckets": ["contact_ready_ab"], "tiers": ["A", "B"], "hasContact": True},
        sort_by="total_score",
        order=120,
    ),
    make_preset(
        "builtin_premium_hosting_ab",
        "Premium hosting A/B",
        "Outreach ready",
        "Higher-priority leads with mature hosting or CDN signals.",
        {"salesBuckets": ["premium_hosting_ab"], "tiers": ["A", "B"], "hasContact": True},
        order=130,
    ),
    make_preset(
        "builtin_high_spend",
        "High spend",
        "Outreach ready",
        "Higher technology-spend accounts worth prioritising first.",
        {"salesBuckets": ["high_spend"], "tiers": ["A", "B", "C"], "hasContact": True},
        sort_by="technology_spend",
        order=140,
    ),
    make_preset(
        "builtin_geo_review",
        "Geo review needed",
        "Review",
        "TLD and country do not line up cleanly, so review before outreach.",
        {"salesBuckets": ["geo_review_needed"], "tiers": ["A", "B", "C", "D"], "hasContact": False},
        sort_by="country",
        sort_direction="asc",
        order=150,
    ),
]
